### ISSUE TITLE
Missing support for bugfix branches

### ISSUE THREAD

**Issue by boekabart** [hightechict/DashDashVersion#6]
**Describe the bug**
git flow `bugfix` branches are equivalent to `featuere` branches.

**To Reproduce**
1. git flow bugfix create "Test"
2. run git-flow-version
3. Lo and behold:
```
Error: System.Exception: git-flow-version failed with error code -1 message: This branch : bugfix/Test is a 'feature' branch, only feature branches of the format 'feature/<name>' are supported. (Parameter 'name')
```
**Expected behavior**
Same as if the branch had been called `bugfix/Test`, smth like `SemVer": "1.1.0-dev.1.Test.1`

**Comment by kees2125** [comment]
I've added support for this option and will include it in the next release
